# Generated by Django 5.1.1 on 2024-09-26 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(max_length=50, verbose_name='Описание'),
        ),
    ]
